language: node_js
node_js:
  - '4.2'
language: csharp
solution: ./Promact.Oauth.Server/Promact.Oauth.Server.sln
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1    
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - if [ -n "${DOTNETCORE}" ]; then dotnet restore && dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests -c Release && dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json -c Release && cd ./Promact.Oauth.Server/src/Promact.Oauth.Server && npm install typings --global && npm install -g typescript && npm install && npm run test; fi