language: csharp
node_js:
- 6.3.1
os: linux		
dist: trusty		
sudo: required
dotnet: 1.0.1
cache:
  yarn: true
  directories:
     - $HOME/build/Promact/promact-oauth-server/Promact.Oauth.Server/src/Promact.Oauth.Server/node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- nvm install 6.3.1
- nvm use 6.3.1
- npm i -g npm@4.5.0
install:
- npm i -g typescript typings
- cd ./Promact.Oauth.Server/src/Promact.Oauth.Server
- npm install
- npm run aot
- cd .. && cd ..
- dotnet restore
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.Oauth.Server/Promact.Oauth.Server.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- cd ./src/Promact.Oauth.Server.Tests 
- dotnet build Promact.Oauth.Server.Tests.csproj -c Release
- dotnet test Promact.Oauth.Server.Tests.csproj -c Release
- cd .. && cd ./Promact.Oauth.Server && npm run tslint && npm run test && npm run codecov