language: csharp
node_js:
- 6
- stable
os: linux		
dist: trusty		
sudo: required
dotnet: 1.0.0-preview2-1-003177
cache:
  yarn: true
  directories:
     - $HOME/build/Promact/promact-oauth-server/Promact.Oauth.Server/src/Promact.Oauth.Server/node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm i -g typescript typings
- dotnet restore
- chmod +x ~/.nuget/packages/xunit.runner.console/2.2.0-beta5-build3474/tools/xunit.console.exe
- sudo apt-get install gtk-sharp2
- curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
- unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
- cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
- cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
- git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
- cd ../../csMACnz/monocov
- cp /tmp/cecil/Mono.Cecil.dll .
- ./configure
- make
- sudo make install
- cd ../../Promact/promact-oauth-server
- ls
- pwd
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.Oauth.Server/Promact.Oauth.Server.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- ls
- pwd
- dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests -c Release
- dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json -c Release 
- xbuild /p:Configuration=Release ./src/Promact.Oauth.Server/Promact.Oauth.Server.sln
- export LD_LIBRARY_PATH=/usr/local/lib
- mono --debug --profile=monocov:outfile=monocovCoverage.cov,+[Promact.Oauth.Server],+[Promact.Oauth.Server.Tests] ~/.nuget/packages/xunit.runner.console/2.2.0-beta5-build3474/toolstools/xunit.console.exe ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/bin/Release/netcoreapp1.0/Promact.Oauth.Server.Tests.dll  /noshadow
- monocov --export-xml=monocovCoverage monocovCoverage.cov
- REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
- REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
- REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
- echo $TRAVIS_COMMIT
- echo $TRAVIS_BRANCH
- echo $REPO_COMMIT_AUTHOR
- echo $REPO_COMMIT_AUTHOR_EMAIL
- echo $REPO_COMMIT_MESSAGE
- echo $TRAVIS_JOB_ID
- mono ./src/packages/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage -- "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci"  --useRelativePaths
- cd ./Promact.Oauth.Server/src/Promact.Oauth.Server && npm install && npm run tslint && npm run test && npm run ci  
env:  
  - secure: DkhgBzCWnOqeA8Rw5FoJ9/CsFusvM6kc8AzeWQDwJi/chAeCc4jlE0ch/t8Otzfzr2/CFFZBGGw3wHoPZUKNvoJZiUyRN9GW2SRkVu/GH3pou1Cs5LyE5HvFDd1jpefYpHjv2R2bqd6iv9zyRkhIC01JyadnYsFiAqNc2VRrZfHG2PGkrQBmz+VWaHBhyMYr26WIJxKiPTN8C7ZZZ7JYd3KrIDKZPxrRog7rNP59qH0Qodqj6G7zqW4hRC9s2XPtlXQQLXBRlrEqUyEQ+NbDTe8NXjVxLoevFpX2X2BkCZDpS19NMvO9nYewqfpkRZkBEHXL7JYWcwyppGGf5sUC3Z2cit4ooR1t/lDzpTv0KfIbHpGY1IStAF0p1rV7JO5MamaqOEMGtt4rF49w5Z1bp8KONGknD57N0l2RsvQMODA4WFQdTVgI/dUO3uwubkjFq5SJelNjb8hk0VXE6dhg01ZvBBpP6LM5eumOgnOMlYco2/X9w2Dz4lA3e6jEASjKLRGRTURR7Xq81/frLrPEb/XbdLgrd6bLiGVIeuOVo79GnvRvZs7NGH1UB5uZjsj+SaeMC7v3BWLcDFzfGtc+tRb5JTIfcFRmYknu4POyrOvZyfGrScz0148Yp0vYtgA8JGUFG7ilTWrfMGNjfihsPzVBtQHBOtYDXuDHlLbifqQ=

 