language: csharp
node_js:
- 6.3.1
os: linux		
dist: trusty		
sudo: required
dotnet: 1.0.1
cache:
  yarn: true
  directories:
     - $HOME/build/Promact/promact-oauth-server/Promact.Oauth.Server/src/Promact.Oauth.Server/node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm i -g typescript typings
- dotnet restore ./Promact.Oauth.Server/src/Promact.Oauth.Server
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.Oauth.Server/Promact.Oauth.Server.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server 
- dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests 
- cd ./Promact.Oauth.Server/src/Promact.Oauth.Server && npm install && npm run tslint && npm run test && npm run codecov
 