
language: node_js
node_js:
  - '0.10.12'
  - '0.12'
  - '4'
  - '6'
language: csharp
solution: ./Promact.Oauth.Server/Promact.Oauth.Server.sln
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1    
notifications:
  email:
    on_success: change
    on_failure: always
    
language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
after_success:
  coveralls 
script:
  - if [ -n "${DOTNETCORE}" ]; then dotnet restore && dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests -c Release && dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json -c Release && cd ./Promact.Oauth.Server/src/Promact.Oauth.Server && npm install typings --global && npm install && npm run test; && coverage run --source=moscowdjango,meetup manage.py test fi