language: csharp
node_js:
- 6
- stable
mono: none
os: linux		
dist: trusty		
sudo: false
dotnet: 1.0.0-preview2-1-003177
cache:
  yarn: true
  directories:
     - $HOME/build/Promact/promact-oauth-server/Promact.Oauth.Server/src/Promact.Oauth.Server/node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm i -g typescript typings
- dotnet restore
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.Oauth.Server/Promact.Oauth.Server.sln"
notifications:
  email:
    on_success: change
    on_failure: always
after_success:
- bash <(curl -s https://codecov.io/bash)
script:
- dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests -c Release
- dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json -c Release 
- cd ./Promact.Oauth.Server/src/Promact.Oauth.Server && npm install && npm run tslint && npm run test --cover  
env:  
- secret:maAaOvUx0qe+WFLercSKsNo206YAlqZP7FGxYK4l6iJjFgsB/pkOuFmAmVlfO+aRYGi9sXgmSHd41rgmNniPujP4GUkcMQDBb8iWHmptk8c=
