language: csharp
solution: ./Promact.Oauth.Server/Promact.Oauth.Server.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: latest
      env: DOTNETCORE=1    

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - dotnet restore && dotnet build ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests -c Release && dotnet test ./Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json -c Release; fi