-version: 1.0.{build}
 -configuration: Release
 -platform: Any CPU
 -test: off
 -build_script:
 -- ps: .\build.ps1
 -notifications:
 -- provider: Slack
 -  auth_token:
 -    secure: a8gvDGvmvaulk5ajhx+cTq9Eebui6VidpqGMXmx7HKu5SHwnSKZGveU/BclA+/hifPjQMWUNyvWIFX8LpSDcPQ==
 -  channel: sci-oauth-dev
 -  on_build_success: true
 -  on_build_failure: true
 -  on_build_status_changed: false
